### ISSUE TITLE
Add sponsor section

### ISSUE THREAD

**Issue by MatiasOS** [blockchain-tandil/homepage#3]
We need to add a new sponsors section. 
Our first sponsor is IDEB Tandil, and here is the logo to add
 
![Logo](https://user-images.githubusercontent.com/5481398/55675022-c67c1180-5892-11e9-8a5f-0a9a90123017.jpg)

**Comment by edisonv19** [comment]
I want to take this

**Comment by MatiasOS** [comment]
closed by #4
